### ISSUE TITLE
utils: multi db configure confusion.

### ISSUE THREAD

**Issue by kfysck** [DTC8/DTC#145]
```
# 
# DTC configure file. v2
#
connection: &connection
  addr: 127.0.0.1:3307
  user: sharding
  pwd: sharding

extension:
  - logic:
      {db: ss_adt, table: 1111, connection: *connection}
    real:
      - {addr: '127.0.0.1:3306', user: root, pwd: '123456', db: ss_adt}
  - logic: 
      {db: ss_cfs, table: 1111, connection: *connection}
    real:
      - {addr: '127.0.0.1:3306', user: root, pwd: '123456', db: ss_cfs}
  - logic: 
      {db: ss_cms, table: 1111, connection: *connection}
    real:
      - {addr: '127.0.0.1:3306', user: root, pwd: '123456', db: ss_cms}
  - logic: 
      {db: ss_cmx, table: 1111, connection: *connection}
    real:
      - {addr: '127.0.0.1:3306', user: root, pwd: '123456', db: ss_cmx}
  - logic: 
      {db: ss_cmz, table: 1111, connection: *connection}
    real:
      - {addr: '127.0.0.1:3306', user: root, pwd: '123456', db: ss_cmz}
  - logic: 
      {db: ss_cnn, table: 1111, connection: *connection}
    real:
      - {addr: '127.0.0.1:3306', user: root, pwd: '123456', db: ss_cnn}
  - logic: 
      {db: ss_ebs, table: 1111, connection: *connection}
    real:
      - {addr: '127.0.0.1:3306', user: root, pwd: '123456', db: ss_ebs}
  - logic: 
      {db: ss_ebx, table: 1111, connection: *connection}
    real:
      - {addr: '127.0.0.1:3306', user: root, pwd: '123456', db: ss_ebx}
  - logic: 
      {db: ss_eim, table: 1111, connection: *connection}
    real:
      - {addr: '127.0.0.1:3306', user: root, pwd: '123456', db: ss_eim}
  - logic: 
      {db: ss_ent, table: 1111, connection: *connection}
    real:
      - {addr: '127.0.0.1:3306', user: root, pwd: '123456', db: ss_ent}
  - logic: 
      {db: ss_enx, table: 1111, connection: *connection}
    real:
      - {addr: '127.0.0.1:3306', user: root, pwd: '123456', db: ss_enx}
  - logic: 
      {db: ss_gis, table: 1111, connection: *connection}
    real:
      - {addr: '127.0.0.1:3306', user: root, pwd: '123456', db: ss_gis}
  - logic: 
      {db: ss_log, table: 1111, connection: *connection}
    real:
      - {addr: '127.0.0.1:3306', user: root, pwd: '123456', db: ss_log}
  - logic: 
      {db: ss_ors, table: 1111, connection: *connection}
    real:
      - {addr: '127.0.0.1:3306', user: root, pwd: '123456', db: ss_ors}
  - logic: 
      {db: ss_pss, table: 1111, connection: *connection}
    real:
      - {addr: '127.0.0.1:3306', user: root, pwd: '123456', db: ss_pss}
  - logic: 
      {db: ss_tkt, table: 1111, connection: *connection}
    real:
      - {addr: '127.0.0.1:3306', user: root, pwd: '123456', db: ss_tkt}
  - logic: 
      {db: ss_uns, table: 1111, connection: *connection}
    real:
      - {addr: '127.0.0.1:3306', user: root, pwd: '123456', db: ss_uns}
  - logic: 
      {db: ss_unx, table: 1111, connection: *connection}
    real:
      - {addr: '127.0.0.1:3306', user: root, pwd: '123456', db: ss_unx}
  - logic: 
      {db: ss_uss, table: 1111, connection: *connection}
    real:
      - {addr: '127.0.0.1:3306', user: root, pwd: '123456', db: ss_uss}      

```
