### ISSUE TITLE
Agent: Merge xml conf file of agent to dtc.yaml.

### ISSUE THREAD

**Issue by kfysck** [DTC8/DTC#54]

**Comment by kfysck** [comment]
New agent conf:
```
props:
  listener.port.agent: 12001
  listener.port.dtc: 20015
  listener.port.extension: 3745

agent:
  group:
    - instance: weather
      machine:
        - addr: dtc:20015
```
